### PR TITLE
Makes the arguments from RAT_main and events data pickleable

### PR DESCRIPTION
**Pull request by StephenNneji**
Addresses part of #73

### CODE REVIEW

**Comment by alexhroom** [comment]
looks good: can now run the following:
```python
from concurrent.futures import ProcessPoolExecutor

import RATapi as RAT


def run(problem_definition, cells, limits, priors, cpp_controls):
    problem_definition, output_results, bayes_results = RAT.rat_core.RATMain(
        problem_definition,
        cells,
        limits,
        cpp_controls,
        priors,
    )

    results = RAT.outputs.make_results("calculate", output_results, bayes_results)

    return results


pool = ProcessPoolExecutor()
project, _ = RAT.examples.DSPC_standard_layers()
c = RAT.Controls()

problem_definition, cells, limits, priors, cpp_controls = RAT.inputs.make_input(project, c)

result = pool.submit(run, problem_definition, cells, limits, priors, cpp_controls)
results = result.result()
print(results)
```

can't quite pickle the entire `Project` object yet: with `dill`, the error I get is that `RATapi.rat_core.EventBridge` is not pickleable. Would it be difficult to make that pickleable too? no worries if it's a lot of trouble to pickle (or you foresee other problems), the above is definitely workable for what we need!

**Review by alexhroom — COMMENTED** [review]
looks good: can now run the following:

```python
from concurrent.futures import ProcessPoolExecutor

import RATapi as RAT


def run(problem_definition, cells, limits, priors, cpp_controls):
    problem_definition, output_results, bayes_results = RAT.rat_core.RATMain(
        problem_definition,
        cells,
        limits,
        cpp_controls,
        priors,
    )

    results = RAT.outputs.make_results("calculate", output_results, bayes_results)

    return results


pool = ProcessPoolExecutor()
project, _ = RAT.examples.DSPC_standard_layers()
c = RAT.Controls()

problem_definition, cells, limits, priors, cpp_controls = RAT.inputs.make_input(project, c)

result = pool.submit(run, problem_definition, cells, limits, priors, cpp_controls)
results = result.result()
print(results)
```

can't quite pickle the entire Project object yet: with dill, the error I get is that RATapi.rat_core.EventBridge is not pickleable. Would it be difficult to make that pickleable too? no worries if it's a lot of trouble to pickle (or you foresee other problems), the above is definitely workable for what we need!

**Comment by StephenNneji** [comment]
I don't fully understand why its trying to pickle the EventBridge when you try to pickle the Project class. The EventBridge manages the callback for the events so pickling this might be a pain and even when its pickled I don't think you can pass callback functions between processes at least I have never tried to

**Review by alexhroom — APPROVED** [review]
no worries then! i don't understand either, but this should do

**Pull request merged**
